- .gitignore
- MoinMoin/storage/stores/_tests/conftest.py
- setup.cfg
- setup.py
also: fix some deprecated stuff, exclude .git directory
> pytest: use latest version < 3.0

- src/moin/converter/rst_in.py
pytest.importorskip('docutils') seems obsolete, if no docutils, many tests should fail
> fix rst_in.py failure due to failed import of pytest

- src/moin/user.py
this should fix the DeprecationWarning about giving additional params
to .hash(). we do not use this for tests.
fixes #657.
> remove unused salt param, we never used a non-default value

- src/moin/converter/_tests/test_docbook_in.py
- src/moin/converter/docbook_in.py
similar code for entry -> table-cell exists, but td was missing.
fixes #626.
> docbook_in: add td -> table-cell

- src/moin/converter/_tests/test_creole_in.py
- src/moin/converter/creole_in.py
not sure how to build a better parsing regex.
the problem is that the table parser splits the table cells at `|`.
when the table cell contains link markup like `[[link_target | link_text]]`, the table parser should not split the cell at the `|` contained in there.
> creole_in: added a commented and failing test for issue #386

- contrib/sample/MoinWikiMacros.data
- src/moin/macros/ItemPageList.py
- src/moin/macros/_base.py
After merging the PR for issue #798, Roger suggested a number of improvements (e.g., removing the numsep parameter, translations, test for non-existence, etc.), all of which are addressed here.  Please take a look at the new sample/MoinWikiMacros page!
I'm waiting a couple more weeks before removing the <<PageNameList>> macro.
One remaining enhancement is to add filtering by tags as yet another filtering mechanism.
> ItemPageList updates per request

- contrib/wsgi/moin2.wsgi
The current script was 3 years old ands referenced the "MoinMoin" app that doesn't exist anymore.
Also cleaned up some of the comments.
> fix moin2.wsgi script

- docs/devel/development.rst
> Fixed broken link

- quickinstall.py
Add shebang line to `./m` on non-windows. Fixes #846 
This prevents it from failing when using non-bash shells.
> Add shebang line to `./m` on non-windows

- src/moin/apps/admin/templates/admin/trash.html
- src/moin/templates/ajaxsearch.html
- src/moin/templates/blog/utils.html
- src/moin/templates/diff_text.html
- src/moin/templates/history.html
- src/moin/templates/utils.html
consistent display of dates, see #831
user may choose iso 8601 formated dates in user settings
> belated conversion of datetimeformat to time_datetime on several views;

- src/moin/themes/basic/templates/layout.html
caused by 2020-03-09 fix to add support for #anchor within urls
> fix traceback in basic theme when modifying an item

- src/moin/forms.py
- src/moin/items/__init__.py
- src/moin/templates/modify.html
- src/moin/themes/basic/templates/modify.html
users should not be allowed to change these meta data fields:
item_id, itemtype, contenttype, namespace, or rev_number
> remove Extra MetaData (JSON) from modify view, fixes #700

- src/moin/converters/_tests/test_markdown_in.py
- src/moin/converters/markdown_in.py
the DIV tags cause paragraph spacing issues and sometimes break tables
> markdown embedded HTML markup must be enclosed in P tags, not DIV tags

- _ui_tests/README.txt
- _ui_tests/conftest.py
- _ui_tests/test_subitems.py
- docs/devel/development.rst
- src/moin/conftest.py
- tox.ini
This PR fixes #912.
I runned `tox` on python 3.7 and it still work ('1644 passed, 29 skipped, 1 xfailed, 2 warnings").
Flake8 passed too.
> replace py.test by pytest

- src/moin/auth/__init__.py
- src/moin/converters/image_in.py
- src/moin/converters/mediawiki_in.py
- src/moin/converters/moinwiki_in.py
- src/moin/items/content.py
- src/moin/storage/middleware/indexing.py
- src/moin/utils/diff_html.py
- src/moin/utils/interwiki.py
- src/moin/utils/send_file.py
- src/moin/wikiutil.py
This PR fixes several `DeprecationWarning` shown when `tox` runs. They are fixed by updating the `import`.
There are still two DeprecationWarnings which can not be fixed this way: one DeprecationWarning is in `flask_theme` dependancy and the other one is about `werkzeug.contrib.atom` module which will be removed in Werkzeug 1.0.
> fix several deprecationWarnings

- setup.py
- src/moin/apps/feed/views.py
This PR uses feedgen library to generation Atom feed.
I checked the tests pass with `tox --recreate` for python 3.7 . The previous output (generated with `werkzeug.contrib.atom.AtomFeed()`) is more or less the same with feedgen output in feed test.
I failed to run moinmoin so I did not see the real output.
Closes: #850
> generate Atom feed with feedgen library instead of Flask

- src/moin/apps/feed/views.py
- src/moin/items/content.py
When the Atom feed includes diff with a previous revision, an exception is raised because `fqname` 
is not defined (see https://github.com/moinwiki/moin/issues/1015).
This patch adds the `fqname` parameter to `Text._render_data_diff_atom()` method (like `Text._render_data_diff_html()` and `Text._render_data_diff()` methods) and uses it.
Closes: https://github.com/moinwiki/moin/issues/1015
> fix Atom feed when feed includes revision

- setup.py
This PR updates Flask-Theme dependancy to the last release which provides `import` compatible with Werkzeug 1.0.
Closes: https://github.com/moinwiki/moin/issues/951
> update Flask-Theme dependancy

- src/moin/_tests/test_wikiutil.py
- src/moin/apps/frontend/_tests/test_frontend.py
- src/moin/items/_tests/test_Content.py
- src/moin/storage/backends/fileserver.py
This PR fixes `ImportError` raised by `tox`if the Werkzeug dependancy is updated to v. 1.0.
It's necessary to update the Werkzeug library but this patch is not enough: it does not fix https://github.com/moinwiki/moin/issues/1020 for example.
> update import for compatibility with Werkzeug 1.0+

- src/moin/utils/forms.py
This PR fixes an import to a version compatible with Werkzeug 1.0+.
It's necessary but not enough to update moin2 to Werkzeug 1.0+: after merging this PR and https://github.com/moinwiki/moin/pull/1021, if you update to Werkzeug 1.0, some unittests fail due to change into Werkzeug.
Closes: https://github.com/moinwiki/moin/issues/1020
> update FileStorage import for Werkzeug 1.0 compatibility

- contrib/wsgi/profiler.py
- setup.py
- src/moin/apps/serve/_tests/test_serve.py
- src/moin/auth/http.py
This PR fixes few `import` and updates a test for compatibility with Werkzeug 1.0 release.
The tests are green (runned on python3.7) and I tried basic actions on the local server (with `./m run`): modifying a page, updating the same page and updating a file.
> update for werkzeug 1.0

- quickinstall.py
`quickinstall.py` has executable rights (`-rwxr-xr-x`) so it's easy to think the script has to be run directly.
With this patch, `./quickinstall` will run the right interpreter if python is a link to python2.
> shebang targets python3 for quickinstall.py

- src/moin/utils/paramparser.py
Implement issue #925.
No additional tests needed as the logic is already tested in `testExtendedParserQuoting()`.
> [#925] parse_quoted_separated_text(): add single quote to default quotes

- src/moin/apps/frontend/views.py
werkzeug removed request.is_xhr because not all javascript libraries
supported it and there is no standard.
> 'Request' object has no attribute 'is_xhr' fix #1030

- src/moin/storage/middleware/indexing.py
This PR just updates some fields defined in `IndexingMiddleware` class. Basically, there are some fields defined in `common_fields` that should be in `ticket_fields` and `blog_entry_fields`. 
Fields moved to `ticket_fields`: `REPLY_TO`, `REFERS_TO` and `ELEMENT`
Fields moved to `blog_entry_fields`:  `PTIME`
Closes #1087
> Issue 1087 whoosh  index  fields  defined  in  wrong  dict

- src/moin/apps/frontend/views.py
- src/moin/items/__init__.py
- src/moin/templates/modify_select_contenttype.html
had to move findMatches, etc from frontend/views.py to items/init.py
to avoid circular import
renamed findMatches to more conventional find_matches
> show similar item names on item create, fixes #109

- src/moin/scripts/migration/moin19/macros/PageList.py
- src/moin/scripts/migration/moin19/macros/_tests/test_PageList.py
- src/moin/scripts/migration/moin19/macros/_tests/test_PageList_migration.py
The moin-1.9 PageList macro passed all arguments to the FullSearch macro which basically means all arguments were handled as regular expressions. This Pull Request fixes the PageList macro migration to only use regular expression arguments for the converted ItemList macro. It also fixes a typo in the converted macro and adds some basic testing for the migration procedure.
> Fix PageList migration to use only regexp arguments

- src/moin/macros/MonthCalendar.py
- src/moin/storage/middleware/indexing.py
This is just an example how to optimize macro runtime mentioned in #1222. 
Requires more discussion before merging. The search_names() function should be moved to another module for reusability.
Reduces runtime from 14 seconds to 3 seconds in a real example for a one year calendar.
> MonthCalendar: optimize performance using index search

- setup.py
run ./m quickinstall after pulling this
> work around for incompatible packages: Babel, docutils; #1239, #1240

- quickinstall.py
run "./m upgrade" after installing this patch to update sphinx to 4.5.0,
pytest to 7.1.2, tox to 3.25.0
> missing --upgrade in quickinstall.py, fixes #1250

- docs/admin/install.rst
> admin.install docs: Correct create-instance syntax and typo

- src/moin/scripts/maint/modify_item.py
This update ensures that wikiname in metadata is build from the target interwikiname setting while running `moin load-help`.
As discussed in #1155.
> kill WIKINAME in load-help

- docs/admin/install.rst
- Added command to install from Test pypi
- Removed section about pypi mirrors, they are not reachable any more
- Improved formatting of code
As mentioned in #1197
> Add test.pypi, remove pypi mirror, formatting

- quickinstall.py
Instead of checking for exactly 'quickinstall.py', I'm now checking if exactly 1 argument was called that ends with quickinstall.py. This should include all relative paths. 
Note that being in the main folder seems to still be necessary, as e.g. calling ..\\..\quickinstall.py won't throw errors but won't work either, however this is not a result from this change (but was already this way before) and is likely much less relevant if users follow the quickinstall instructions.
> Fix quickinstall not working if called with path

- quickinstall.py
When quickinstall.py is run with parameter --FirstCall the redirect of stdout and stderr is already done. No need for a second redirect to the same logfile. Obviously this is a problem with Ubuntu 22.04 LTS desktop version.
Tested with Ubuntu 22.04 desktop and Debian 11 Server version. Please assist with tests on Windows.
> quickinstall.py: remove recursive log file open

- src/moin/utils/filesys.py
werkzeug.posixemulation has been removed in werkzeug 2.0.0, see 
https://werkzeug.palletsprojects.com/en/2.2.x/changes/#version-2-0-0
Prepare for werkzeug >= 2.0 and related to https://github.com/moinwiki/moin/issues/1109.
> Use os replace instead of werkzeug.posixemulation rename

- src/moin/apps/feed/views.py
- src/moin/apps/frontend/views.py
- src/moin/auth/__init__.py
- src/moin/items/__init__.py
- src/moin/items/ticket.py
- src/moin/utils/forms.py
'jinja2.Markup' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.
Prepare for Jinja2 >= 3.0 and related to #1109.
> Replace Jinja2.Markup with markupsafe.Markup

- src/moin/converters/image_in.py
- src/moin/converters/mediawiki_in.py
- src/moin/converters/moinwiki_in.py
Parameter encode_keys was related to unicode and ignored since python 3.x.
Prepare for Werkzeug 2.x and related to #1109.
> Remove deprecated encode_keys parm from werkzeug.urls.url_encode

- src/moin/apps/frontend/_tests/test_frontend.py
- src/moin/apps/serve/_tests/test_serve.py
doctype string has been changed to lowercase in Werkzeug 2.1.2, see 
https://github.com/pallets/werkzeug/pull/2391/files
The if statement in line 42 is a workaround to allow all versions and can be removed when 2.1.2 is minimum version in setup.py. 
Prepare for Werkzeug 2.x and related to #1109.
> Fix doctype in test_frontend.py for Werkzeug >= 2.1.2

- docs/requirements.txt
- setup.py
Change dependencies to upgrade to newer versions as discussed in #1109
- Flask                         2.0.3
- Flask-Script               2.0.5
- Jinja2                        3.0.3
- MarkupSafe               2.1.2
- Werkzeug                   2.1.2
Hopefully it also fixes #1333, my tests with `./m docs` run successfully in Debian 11.
Please support with testing in different environments.
> Upgrade versions in setup.py

- docs/requirements.txt
sphinx-rtd-theme 1.2.0 is released now. 
Fixes #1333.
> Use sphinx-rtd-theme >= 1.2.0

- docs/admin/backup.rst
- docs/admin/index.rst
- docs/admin/install.rst
- docs/admin/requirements.rst
- docs/admin/serve.rst
- docs/devel/development.rst
- docs/intro/features.rst
- docs/man/moin.rst
- src/moin/app.py
- src/moin/config/wikiconfig.py
Updated documentation after migration from flask-script to cli, see #729.
Most changes have been made in `docs/man/moin.rst`.
I am aware that there are different opinions which cli interface is the better or newer one. Removed the words newer and older. For me the ./m interface is needed by developers and the moin cli is the only interface for normal wiki users. Hope this change is ok.
> CLI: update docs and comments

- src/moin/help/en/html.meta
do `moin load-help -n en` to repair wiki instance
> loading moin help-en docs makes default html item disappear: fixes #1357

- setup.py
- src/moin/macros/_tests/test_Date.py
- src/moin/macros/_tests/test_DateTime.py
- src/moin/utils/_tests/test_show_time.py
> Raise Babel version, allow no-break space and upd year in test data

- setup.py
- src/moin/app.py
Moving the before_request and teardown_request registration from blueprint to app object solves issue #1383.
Please check and approve. I don't have much experience in this area.
> Update to flask 2.2.3

- src/moin/help/welcome/Home.meta
The welcome page also had an invalid parentid causing the `'server overload or corrupt index'` error in `src/moin/storage/middleware/indexing.py:120` as mentioned in #1375. The feed using http://localhost:5000/+feed/atom is now running without complaints.
> Home.meta: remove obsolet parentid

- src/moin/cli/_tests/__init__.py
- src/moin/cli/_tests/conftest.py
- src/moin/cli/_tests/data/Corrupt.data
- src/moin/cli/_tests/data/Corrupt.meta
- src/moin/cli/_tests/test_serialization.py
- src/moin/cli/maint/modify_item.py
- src/moin/cli/maint/serialization.py
- src/moin/help/welcome/Home.meta
xfail tests for #1402
fix for help/welcome/Home.meta size
altering --path parameter on load-help
now works same as dump-help
changing -a to flag for save
appears this is how it is expected to work in quickinstall.py
fix for save with no -f option use stdout.buffer to output binary data
> test for cli load and save, #1387

- src/moin/translations/de/LC_MESSAGES/messages.po
Currently, the E-Mail Password-Reset-Notification is missing a space:
Trying to recover the password of UserName leads to:
Eine E-Mail zur Wiederherstellung des Passwortes wurde anUserName gesendet.
This PR changes this to:
Eine E-Mail zur Wiederherstellung des Passwortes wurde an UserName gesendet.
TL;DR:
Fix missing space
> Fix missing space in german translation.

- setup.py
- src/moin/utils/_tests/test_interwiki.py
Workaround: substitute '%40' with '@' to allow both Werkzeug versions 2.2. and 2.3.
Pin Werkzeug to < 2.4.0. There are a lot of deprecated warnings.
Fixes #1421
> test_interwiki: do not encode at sign

- src/moin/translations/MoinMoin.pot
- src/moin/translations/de/LC_MESSAGES/messages.po
- src/moin/utils/edit_locking.py
Removed blanks and linefeed in utils/edit_locking.py.
Updated catalog using
```
python setup.py extract_messages
python setup.py update_catalog -l de
```
and added some German translations related to edit locking.
Other languages should be supported by native speakers. 
Related to #651.
> Update message catalog and German translations

- src/moin/cli/maint/dump_html.py
avoids users/Home used as _Home.html rather than default Home
> trivial change to item sort in dump_html.py

- docs/admin/configure.rst
- docs/admin/install.rst
- docs/admin/serve.rst
- docs/user/moinwiki.rst
Fixes some errors and warnings from the RTD build logs.
Correction of built-in server options in serve.rst. Please check if I am right.
Related to #1440.
> Fix some RTD warnings and built-in server options in serve.rst

- src/moin/app.py
As of werkzeug 2.0, the parsed data of request.user_agent has been deprecated. request.headers.get('User-Agent' returns a string if user-agent is a browser, none if a command or test.
> Auto Scroll fails, data-lineno attribute missing, fixes #1449

- docs/admin/maintenance.rst
- requirements.d/development.txt
- src/moin/_tests/__init__.py
- src/moin/cli/_tests/__init__.py
- src/moin/cli/_tests/conftest.py
- src/moin/cli/_tests/data/MyPage-vblank.meta
- src/moin/cli/_tests/data/MyPage-vblank2.meta
- src/moin/cli/_tests/scrapy/moincrawler/spiders/ref_checker.py
- src/moin/cli/_tests/test_modify_item.py
- src/moin/cli/_tests/test_scrapy_crawl.py
- src/moin/cli/_util.py
- src/moin/cli/maint/modify_item.py
- src/moin/conftest.py
- src/moin/storage/middleware/_tests/test_indexing.py
- src/moin/storage/middleware/_tests/test_protecting.py
- src/moin/storage/middleware/indexing.py
- src/moin/storage/middleware/validation.py
repairing parentid for destroy rev, fixes #1448
also updating maint-validate-metadata, final fix for #1402
* updating index when fixing items
* not replacing revision numbers for gaps in sequence
> repairing parentid for destroy rev, fixes #1448

- src/moin/converters/_tests/test_docbook_in.py
- src/moin/converters/docbook_in.py
- src/moin/converters/html_in.py
TODO: help-en items that do not show Item Links must be modified and saved.
> docbook, html do not show Item Links in metadata #1259

- src/moin/cli/_tests/conftest.py
one remaining extra index-build after load-help for #1458
> removing index-build after load-help, fixes #1458

- src/moin/cli/_tests/test_modify_item.py
- src/moin/cli/_tests/test_scrapy_crawl.py
also enabling scrapy test, please provide logs of failure if this test continues to be troublesome
> insuring sort by MTIME in cli tests, fixes #1471

- setup.py
Workaround for #1515.
New version of setuptools_scm has been released today. CI workflow is failing.
> add workaround: use setuptools_scm < 8.0

- src/moin/converters/_tests/test_markdown_in.py
the markdown test cases were missing tests for the table extension
> Tests: add test case for markdown tables

- src/moin/items/_tests/test_Content.py
- src/moin/items/_tests/test_Item.py
- src/moin/items/content.py
- src/moin/templates/modify_select_contenttype.html
This is a first draft for #1500.
I am still looking for a solution to move the `ENABLED_CONTENT_TYPES` variable into the configuration. It seems to be a problem because content_type registration is done before configuration is available.
I look forward to your comments and advice.
> WIP: add feature to enable selected content types

- docs/user/markdown.rst
- setup.py
- src/moin/converters/_tests/test_markdown_in.py
- src/moin/converters/markdown_in.py
For easier internal wiki links, activate the wikilink extension https://github.com/neurobin/mdx_wikilink_plus Previously, an internal link had to be: `[OtherPage](OtherPage)` now, this works too `[[OtherPage]]` and `[[Page/Subpage]]`
The wikilink extension of python-markdown itself (https://python-markdown.github.io/extensions/wikilinks/) is minimal and does not handle links with slashes in their name, so no subpages.
The complexity of creating the internal wiki links was/is one of the blockers of our upgrade to Moin 2.
The chosen wikilinks extension is listed at https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions and did fit the purpose best. Unfortunately, upstream made clear multiple times that their wikilink extension will stay as it is and not be extended (e.g. …
> markdown: use wikilink extension

- setup.py
> setuptools_scm: revert workaround, use relative path for _version.py

- src/moin/templates/modify.html
the doubleclick feature is only for the show-page to open the modify-view
but the function was also enabled on the modify-view itself, leading to page reload (on a mis-click: data loss) of the same modify page
fixes moinwiki/moin#1512
> remove doubleclick on modify page

- docs/user/markdown.rst
- src/moin/converters/_tests/test_markdown_in.py
- src/moin/converters/markdown_in.py
- src/moin/static/css/common.css
the Admonition extension is built in the markdown-parser: https://python-markdown.github.io/extensions/admonition/ This PR enables the extension and adds documentation to it, as well as tests
The rst admonitions don't handle titles, so the documentation can't contain examples for this feature.
> Markdown: Enable Admonition extension

- src/moin/templates/show.html
Only activate double-click feature pages with rendered content, not on meta-pages such as convert, rename etc
fixes moinwiki/moin#1545
> Limit double-click feature to item view

- docs/user/markdown.rst
the first table example (markup description) was wrong.
Also makes the explanation of the non-supported table alignment in rst clearer in what it means for this docs section
> docs: fix markdown table example

- src/moin/translations/de/LC_MESSAGES/messages.po
Add some missing strings
Simplify a few translations
and consolidate the mixed translation of namespace: one occurrence of it was translated, others weren't. So translate all for consistency
> Add various missing German translations, consolidate and simplify existing ones

- src/moin/items/__init__.py
> Reject preview of empty items to prevent traceback and http 500

- src/moin/forms.py
- src/moin/items/__init__.py
- src/moin/templates/modify.html
- src/moin/themes/basic/templates/modify.html
This reverts commit dd3532629f79074a651e6d16bf405e36ec8cbfb8.
Added 2 mods to revert:
* items/__init__.py added try/TypeError block near line 829
* templates/modify.html added test for item names ending in Group/Dict near line 71
> Revert "remove Extra MetaData (JSON) from modify view, fixes #700"

- docs/admin/configure.rst
- src/moin/constants/keys.py
- src/moin/datastructures/backends/_tests/test_wiki_dicts.py
- src/moin/datastructures/backends/wiki_dicts.py
- src/moin/help/en/WikiDict.data
- src/moin/help/en/WikiDict.meta
- src/moin/items/__init__.py
- src/moin/macros/GetVal.py
- src/moin/macros/_tests/test_GetVal.py
- src/moin/templates/modify.html
- src/moin/templates/utils.html
for items with names ending in Dict or Group
renamed all instances of poorly named somedict/SOMEDICT to wikidict/WIKIDICT.
`>>>>>`Any existing wiki's using Extra Metadata (JSON) must be reworked to use UserGroup.
Updated docs.
`>>>>>`Developers must reload help-en (WikiDict) to avoid display errors.
fixes #1554
> removed Extra Metadata (JSON), replaced with Wiki Dick and User Group

- src/moin/cli/migration/moin19/import19.py
- src/moin/constants/rights.py
This is related to #1561 (4).
On import of moin 1.9 wiki data ACL strings with incorrect capitalization like e.g. 'ALL:' or 'all' are converted to 'All:'
> import19: correct capitalization of special users

- src/moin/cli/migration/moin19/import19.py
related to  #1577.
Conversion of subscriptions will use following keywords with this change:
- `'name'` if old subscription does not use any regex
- `'nameprefix'` if old subscription ends with `'.*'` but not `'/.*'` and does not use any other regex 
- `'namere'` in any other case
> import19: fix subscription migration rules

- .github/workflows/ci.yml
- docs/admin/install.rst
- docs/admin/requirements.rst
- quickinstall.py
- setup.py
- src/moin/__init__.py
- tox.ini
...
and remove get_pip_version() from quickinstall.py.
Related to #1570.
> Raise python version from 3.8+ to 3.9+

- src/moin/cli/migration/moin19/import19.py
- src/moin/converters/moinwiki_out.py
Related to #1585.
This adds a line to the migration statistics, for example:
```
INFO moin.cli.migration.moin19.import19 Migration statistics:
[...]
INFO moin.cli.migration.moin19.import19 Warnings:         3 - unknown macros 'TitleIndex', 'Action', 'SystemAdmin'
```
> import19: check for unknown macros

- src/moin/templates/show.html
Double click: Disable when forms are displayed
effectively disables the double click feature on rename and delete action pages
fixes #1598
> Disable Double click on rename and delete pages

- src/moin/macros/ItemList.py
- src/moin/macros/RandomItem.py
- src/moin/macros/TitleIndex.py
- src/moin/macros/_base.py
related to #1585.
Documentation, help-en updates and tests will follow.
> Add macro TitleIndex

- src/moin/config/wikiconfig.py
> change wikiconfig.py using caps to show where ACL changes are needed;

- src/moin/macros/_base.py
- src/moin/macros/_tests/test__base.py
> Raise ValueError when block macros are used inline

- src/moin/cli/migration/moin19/import19.py
... and fix itemlink migration for subitems (e.g. for users namespace)
Related to #1597.
> import19: add target namespace parameter

- src/moin/config/wikiconfig.py
Fixed a typo for the namespace name in root_mapping and 
changed to unique indentation in acls dict.
Related to #1605.
> fix root_mapping and optimize indentation

- src/moin/apps/frontend/views.py
- src/moin/storage/middleware/indexing.py
> fix handling of subscription validation errors

- docs/admin/install.rst
- docs/admin/serve.rst
- docs/devel/development.rst
- quickinstall.py
...
and change default port from 8080 to 5000 in the docs.
> Remove index and run subcommand from quickinstall.py and docs

- docs/admin/backup.rst
- docs/admin/index.rst
- src/moin/cli/_tests/test_serialization.py
- src/moin/cli/_util.py
- src/moin/cli/maint/serialization.py
- src/moin/cli/migration/moin19/import19.py
- src/moin/converters/_util.py
- src/moin/converters/docbook_in.py
- src/moin/converters/markdown_in.py
- src/moin/converters/rst_in.py
> CLI: add index build to load command

- src/moin/storage/middleware/protecting.py
Related to #1645.
This is a prerequisite for whoosh-reloaded as the lru_cache function has been removed long time ago, see https://github.com/Sygil-Dev/whoosh-reloaded/commit/f41d03bed04be3b9042cf995b13444034bb8d518.
> Changing the use of whoosh lru_cache to lfu_cache

- pyproject.toml
setuptools and setuptools_scm are required in the build-system section.
> pyproject.toml: remove setuptools from install dependencies

- src/moin/cli/maint/modify_item.py
Fixes #1684.
Removed temporary import from #1479:
`from __future__ import annotations`
We already dropped Python 3.8 support.
> maint-validate-metadata: skip userprofiles backend

- pyproject.toml
- src/moin/storage/backends/_tests/test_stores.py
- src/moin/storage/stores/sqla.py
> Support for SQLAlchemy 2.0

- src/moin/app.py
- src/moin/constants/misc.py
- src/moin/converters/link.py
- src/moin/templates/utils.html
- src/moin/themes/__init__.py
Related to #1699.
It is hard to solve the problem with class non-existent. I added a hack in lines 205f of `converters/link.py` to show a possible solution for view '+meta', for example. IMO adding a dictionary with view_names and endpoint-function-names seems to be too complex. 
Any ideas on how to improve this? Need help.
> Fix moin-nonexistent class in itemlinks starting with '+'

- src/moin/static/css/common.css
- src/moin/templates/layout.html
- src/moin/templates/search.html
The button "search-options" was using fontawesome before.
Also related to #1704.
> Fix search-options font and apply some W3C recommendations

- src/moin/contrib/intermap.txt
- src/moin/themes/__init__.py
the previous page usemod.com is no longer in use by the original owners and is now used for promotion of gambling
the original authors and owners now use usemod.org and meatballwiki.org for the same purpose
this PR changes the URLs in the code to the new destinations
this does *not* change the URLs also in the installations themselves, which all need to be update manually
fixes https://github.com/moinwiki/moin/issues/1729
> replace usemod[.]com with usemod.org / meatballwiki.org

- src/moin/contrib/intermap.txt
The Website httpX://parawiki[.]org/ promotes a Thai gambling service
It's similar to https://github.com/moinwiki/moin/issues/1729
> Remove parawiki[.]org (Thai gambling) from intermap.txt

- src/moin/cli/migration/moin19/import19.py
> import19: migrate links only if targetnamespace is specified

- src/moin/apps/frontend/views.py
- src/moin/macros/SlideShow.py
- src/moin/templates/slideshow.html
> SlideShow: use url_for()

- src/moin/app.py
- src/moin/utils/clock.py
Skip the before_wiki and teardown wiki handling for static content such as CSS files.
The before_wiki function is needed to open the storage, set up the user - important for ACL handling, setting up the Jinja environment, etc.. The static content is public and therefore the before_wiki and teardown_wiki code is unnecessary overhead. 
The request_path / url has been added to the timer message in the debug log.
Moved clock stop to the end of teardown_wiki. Is there a reason for the existing code sequence?
Related to #1725.
> app.py: skip before_wiki and teardown_wiki for static content

- src/moin/converters/moinwiki_in.py
> moinwiki_in.py: ignore the closing stroke tag if no opening tag found

- src/moin/static/css/common.css
- src/moin/templates/modify.html
- src/moin/templates/modify_meta.html
- src/moin/translations/MoinMoin.pot
- src/moin/translations/de/LC_MESSAGES/messages.po
- src/moin/translations/pt_BR/LC_MESSAGES/messages.po
- src/moin/translations/ru/LC_MESSAGES/messages.po
In most forms the buttons to confirm or cancel are at the bottom because in western countries we read from top to bottom. Because of that this PR moves the buttons for confirmation, cancellation and preview to the bottom. It also changed the order of the buttons because usually a button on the right lets users do anything to go on and a button on the left lets them go back. It also has to do something with how we read (from left to right; the right site is the "future").
Only the button to recover the draft stays at the top since it should be near the message which tells you that you can recover a draft.
~~The next change is that I also moved the alerts to the bottom because the feedback has to be where the buttons for interaction are.~~ (This causes problems, see discussion below) …
> Improve modify layout

- src/moin/converters/_tests/test_markdown_in.py
- src/moin/converters/markdown_in.py
instead of only checking only for the existence of `<`, check for text directly behind the opening bracket and a closing bracket.
This prevents added paragraphs/new lines with just brackets or "arrows" (`<-`) in lines.
fixes https://github.com/moinwiki/moin/issues/1761
> markdown: stricter detection of embedded markup

- docs/user/creolewiki.rst
- docs/user/moinwiki.rst
- src/moin/macros/ItemList.py
- src/moin/macros/_base.py
The inverse of "skiptag", allow for a "tag" parameter so that ItemList() only displays items that have been tagged accordingly.
`<<ItemList(tag="foo")>>`
> Add "tag" parameter to ItemList macro

- src/moin/config/wikiconfig.py
changed single quotes to douple quotes,
wrapped long import statements,
> mass changes generated by ruff when updating moin/config/wikiconfig.py

- src/moin/apps/frontend/views.py
- src/moin/items/__init__.py
- src/moin/items/blog.py
- src/moin/security/__init__.py
- src/moin/storage/middleware/protecting.py
- src/moin/templates/history.html
- src/moin/templates/itemviews.html
- src/moin/templates/show.html
Related to #1725 and #1778.
The changes in items/blog.py need to be tested. I did not find any documentation or status of the blog functionality.
> move 'user.may.write' and 'destroy' call from template to views.py

- src/moin/_tests/test_user.py
- src/moin/apps/frontend/views.py
- src/moin/templates/utils.html
- src/moin/themes/__init__.py
- src/moin/themes/_tests/test_navi_bar.py
- src/moin/user.py
Related to #1781.
The cleanup of the code related to the “exists” field will be done later.
> Deactivate exists checks for page trail and ignore non-existent items

- src/moin/cli/migration/moin19/import19.py
> import19: add exception handling for drop_and_recreate_index

- src/moin/cli/migration/moin19/import19.py
- src/moin/wikiutil.py
> import19: add missing parents

- src/moin/user.py
Fixes #1801
... and also #1788.
This fix enables an update from an old version prior to commit https://github.com/moinwiki/moin/commit/8405c2b8135d8cbc428000b7b3f8c573e07740e3 without cleanup of the browser history.
> page_trail: add type checks

- src/moin/help/help-en/MoinWikiMacros.data
- src/moin/help/help-en/MoinWikiMacros.meta
- src/moin/macros/_base.py
> Fix search result highlighting for itemlist macro

- src/moin/macros/ItemList.py
- src/moin/macros/_base.py
Related to #1809.
The usage of the _args_wiki parser changes the handling of quotes. For most arguments except regex there is no difference if quotes are used or not. E.g. following parameters are valid: `ordered="False"` or `ordered='False'` or `ordered=False`.
> ItemList: use _args_wiki parser

- src/moin/apps/frontend/views.py
- src/moin/templates/404.html
- src/moin/templates/show_nonexistent.html
- src/moin/themes/__init__.py
- src/moin/translations/MoinMoin.pot
- src/moin/translations/de/LC_MESSAGES/messages.po
- src/moin/translations/pt_BR/LC_MESSAGES/messages.po
- src/moin/translations/ru/LC_MESSAGES/messages.po
To prevent information leaks, show a more generic message to users if they have no permissions to a resource does not exist and they have no access to
fixes https://github.com/moinwiki/moin/issues/1728
> Same messages for not found and access denied

- src/moin/items/__init__.py
- src/moin/macros/ItemList.py
- src/moin/macros/_base.py
- src/moin/storage/middleware/indexing.py
- src/moin/storage/middleware/protecting.py
> ItemList performance: mv regex handling to search_meta

- src/moin/cli/__init__.py
- src/moin/cli/maint/create_instance.py
> remove subprocess call from create_instance

- src/moin/utils/send_file.py
> Rework of the send_file exception handling

- docs/admin/configure.rst
- src/moin/config/default.py
- src/moin/config/wikiconfig.py
- src/moin/user.py
> Use new gravatar hash routine

- src/moin/apps/frontend/views.py
- src/moin/templates/blank.html
...
- sorted robots.txt
- removed TODOs. IMO the handling of a next page is obsolete if a blank page is always displayed.
Fixes #1805.
> Show blank page after password reset

- src/moin/apps/admin/templates/user/index_user.html
- src/moin/templates/index.html
- src/moin/themes/__init__.py
previously USERPROFILES ns was shown as grayed and not selectable
> do not show USERPROFILES ns within a list of selectable namespaces #60

- .github/workflows/bandit.yml
Used a customized copy of the action.yml from https://github.com/PyCQA/bandit-action.
The use of bandit-action was not possible because it uses Python 3.9. Reading the configuration in pyproject.toml requires an additional installation step for toml. This tool is integrated in Python since 3.11. If bandit-action raises the Python version, we can switch to bandit-action later.
Bandit results do not abort the workflow, it is terminated with success. The results are imported into the github security area using a sarif file. This area is protected and not publicly accessible. Tested with branch name 'test-github-action'.
> Add bandit scan to github workflow

- docs/admin/configure.rst
- src/moin/app.py
- src/moin/apps/admin/views.py
- src/moin/apps/frontend/views.py
- src/moin/config/default.py
- src/moin/config/wikiconfig.py
Related to #1816.
This implementation uses 'report-uri'. Many tests with 'report-to' did not provide the expected results.
Successfully tested with Chromium 133.0.6943.53 and Firefox 135.0-2.
Tests included items Home, help-en/Home and +admin.
> Add CSP header and receiver

- README.md
Bugfix for #1842.
The logo is not showing in pypi.org and the link to CONTRIBUTING.md does not work.
> README.md: add absolute urls for pypi

- src/moin/cli/migration/moin19/import19.py
- src/moin/cli/migration/moin19/macros/FullSearch.py
- src/moin/cli/migration/moin19/macros/_tests/test_FullSearch_migration.py
- src/moin/macros/ItemList.py
Related to #1585.
The moin1.9 FullSearch macro is used in various situations. One case is the listing of all pages for a specific category. In moin2, the categories are replaced by tags. Therefore, all macro calls related to categories are converted to the moin2 macro ItemList.
In all other cases, the FullSearch macro call is not changed. The same applies to the FullSearchCached macro.
In moin1.9 it is possible to use Categories written as a link, e.g.
```
----
[[CategorySample]]
```
In this case the import19 migration keeps the opening brackets in the item and adds the closing brackets to the category name. This is also fixed with this PR.
> Add FullSearch macro migration for moin1.9 categories

- src/moin/converters/_tests/test_everything.py
- src/moin/converters/everything.py
The converter for binary content (moin.converters.everything) in moin version 2.0.0b2 ignores the item namespace when creating the dom content. The result is an invalid download link when viewing the subitem.
Downloads are working when using the fully qualified item name.
Question in this context: shouldn't the link text created for downloading be localized? Currently it seems to hard-coded to "Download \<item-name\>."
> Fix download link for binary content (missing namespace)

- src/moin/apps/frontend/views.py
The PR fixes a `NameError: name 'revs' is not defined` when attempting to view a diff against a bookmarked history entry.
> Fix undefined name 'revs' in diff view

- src/moin/templates/itemviews.html
Related to #1778.
This avoids one of the whoosh index queries and provides a small performance improvement for large wikis.
> remove exists check from itemviews template

- src/moin/cli/maint/dump_html.py
Attempts to fix the issue with dumping binary content as described in #1742.
While testing dump-html I ran into another issue:
A text file with file extension ".txt" attached as a subitem is being rendered into html content and put into the index.
When the index page is created later on, the href pointing to the text rendered into html still uses the file extension ".txt".
Following such a link in the browser won't render as html page. You will get the raw html text instead.
I will address this issue in a separate PR.
> Fix dump-html: remove item id of links to binary data (#1742)

- src/moin/apps/frontend/views.py
This PR implements the feature requested in #1532 .
The list of existing features available in the user settings form now begins with "(System Default)".
> User settings: support setting the theme name to 'system default' (#1532)

- src/moin/_tests/__init__.py
> Improve the check in get_open_wiki_files()

- .pre-commit-config.yaml
- pyproject.toml
Changing the pre-commit config is required in addition because files passed by the commit hook to bandit via the command line are always checked despite being excluded by the configuration.
See: [Skip tests folder on pre-commit](https://github.com/PyCQA/bandit/issues/912)
> Exclude UI tests in the bandit configuration

- docs/admin/configure.rst
This PR improves the documentation related to logging configuration, addressing issue #1878.
> Improve Logging Configuration Docs: Add MOINLOGGINGCONF and Debug Logging Example

- docs/user/search.rst
- src/moin/apps/frontend/views.py
- src/moin/constants/namespaces.py
- src/moin/static/css/common.css
- src/moin/static/js/search.js
- src/moin/templates/search.html
added clickable options for namespaces and trash
> search query: add some more clickable options, fixes #60

- src/moin/items/content.py
Related to #1858.
For some obvious cases, the Bandit B704 warning is ignored.
> sanitize Markup() input and ignore bandit B704

- src/moin/static/js/common.js
- src/moin/templates/modify_text.html
- src/moin/themes/basic/templates/modify_text.html
Picking up the suggestion made in https://github.com/moinwiki/moin/issues/1770.
> Persist view state of sidebar elements in browser local storage

- src/moin/static/css/common.css
- src/moin/templates/utils.html
- src/moin/themes/focus/static/css/theme.css
Before this PR the help link looked like a button and only if you hovered over it you saw that it is a link. This could confuse users because they expected different behavior.
Before:
After:
> Make help link look like link

- pyproject.toml
- src/moin/app.py
- src/moin/apps/frontend/views.py
- src/moin/cli/_tests/__init__.py
- src/moin/converters/link.py
- src/moin/log.py
- src/moin/storage/middleware/indexing.py
- src/moin/utils/interwiki.py
- src/moin/utils/iri.py
- src/moin/wikiutil.py
Add more type hints to moin in order to help better understand the existing source code.
> Add more type hints

- src/moin/app.py
- src/moin/themes/focus/templates/itemviews.html
> Improve themes

- src/moin/converters/rst_in.py
In Moin 2, the rST converter uses a `NodeVisitor` class instead of a `Writer` class to generate the Moin DOM tree.
Remove the now useless definition of `converters.rst_in.Writer`.
> Remove leftover class definition from rST converter.

- src/moin/themes/focus/static/js/main.js
- src/moin/themes/focus/templates/layout.html
add "use strict" to main.js; fixes #1944
> change focus theme layout.html to load main.js after other scripts

- src/moin/_tests/test_views.py
- src/moin/apps/frontend/views.py
- src/moin/static/css/common.css
- src/moin/templates/ajaxsearch.html
Implements feature request [#1885](https://github.com/moinwiki/moin/issues/1885) by enabling users to scope searches to a specific item and its subitems using a > prefix (e.g., >Lectures design patterns). Includes:
- Query parsing and scoping logic
- UI message update for scoped searches
- Unit tests for query parsing
RESOLVES #1885
> Add support for scoped subitem search using > prefix

- src/moin/apps/frontend/views.py
> prevent IndexError in search when wiki contains deleted items #1885

- src/moin/apps/frontend/views.py
- src/moin/templates/ajaxsearch.html
reworked frontend/views.py searching
User can enter leading namespace in simple query string. 
Converted confusing use of filters to plain query.
Eliminated use of item_name in URL.
Removed non-working code to search transcluded items.
> Search does not support namespaces fixes #1907

- babel.cfg
- docs/devel/translate.rst
- pyproject.toml
Babel >= 2.16.0 (from 2024-08) supports this.
https://github.com/python-babel/babel/pull/1108
> babel: move config to pyproject.toml

- src/moin/_tests/test_user.py
- src/moin/constants/itemtypes.py
- src/moin/items/_tests/test_Blog.py
- src/moin/items/blog.py
- src/moin/user.py
Userprofile items: set properties ITEMTYPE and REV_NUMBER at creation.
Use existing itemtype constants in blog.py.
> Some Itemtype related code changes

- src/moin/storage/middleware/indexing.py
Fixes #1017.
- The function get_indexer() becomes get_doc().
- A new parameter retry is added to get_doc().
- The retry and timeout in get_doc() only apply to calls from store_revision. At the end of this method, the revision that has just been written to the backend is read again. This ensures that this revision exists. In all other cases, e.g., when calling with an invalid, non-existent revid, get_doc immediately triggers a KeyError.
> Rename and rework get_indexer function
