moinwiki/moin

.travis.yml, MoinMoin/_tests/test_wikiutil.py, MoinMoin/auth/_tests/test_ldap_login.py, MoinMoin/converter/_tests/test__args_wiki.py, MoinMoin/converter/_tests/test__wiki_macro.py, MoinMoin/converter/_tests/test_creole_in.py, MoinMoin/converter/_tests/test_csv_in.py, MoinMoin/converter/_tests/test_docbook_in.py, MoinMoin/converter/_tests/test_docbook_out.py, MoinMoin/converter/_tests/test_html_in.py, MoinMoin/converter/_tests/test_html_in_out.py, MoinMoin/converter/_tests/test_html_out.py, MoinMoin/converter/_tests/test_markdown_in.py, MoinMoin/converter/_tests/test_mediawiki_in.py, MoinMoin/converter/_tests/test_moinwiki19_in.py, MoinMoin/converter/_tests/test_moinwiki19_in_20_out.py, MoinMoin/converter/_tests/test_moinwiki_in.py, MoinMoin/converter/_tests/test_moinwiki_in_out.py, MoinMoin/converter/_tests/test_moinwiki_in_out_todo.py, MoinMoin/converter/_tests/test_moinwiki_out.py, MoinMoin/converter/_tests/test_rst_in.py, MoinMoin/converter/_tests/test_rst_in_out.py, MoinMoin/converter/_tests/test_rst_out.py, MoinMoin/converter/_tests/test_smiley.py, MoinMoin/storage/middleware/_tests/test_routing.py, MoinMoin/storage/middleware/_tests/test_serialization.py, MoinMoin/storage/stores/_tests/conftest.py, MoinMoin/storage/stores/_tests/test_kt.py, MoinMoin/util/_tests/test_paramparser.py, setup.py
huge change, but most stuff was rather mechanic.
i commented the more difficult places, asking for feedback.
fixes #584.
=> upgrade pytest 2.x -> 3.x

setup.cfg, tox.ini
the ignores make the current sourcecode pass the checks.
=> tox: add flake8 for checking

src/moin/script/maint/dump_html.py
it directly imported wikiconfig instead of using app.cfg.
also, the path to the moin src needed adjusting
=> fix moin dump-html

setup.cfg, src/moin/apps/frontend/views.py, src/moin/auth/_tests/test_ldap_login.py, src/moin/forms.py, src/moin/items/ticket.py, src/moin/macro/_tests/test_Anchor.py, src/moin/macro/_tests/test_DateTime.py, src/moin/macro/_tests/test_GetText.py, src/moin/macro/_tests/test_GetVal.py, src/moin/macro/_tests/test_Verbatim.py, src/moin/macro/_tests/test__base.py, src/moin/script/migration/moin19/import19.py, src/moin/search/_tests/test_analyzers.py, src/moin/signalling/__init__.py, src/moin/signalling/log.py, src/moin/storage/middleware/indexing.py, src/moin/storage/stores/sqlite.py, src/moin/user.py, src/moin/util/_tests/test_mime.py, src/moin/util/_tests/test_registry.py, src/moin/util/filesys.py, src/moin/util/rev_navigation.py
existing star imports:
- either fixed,
- or added a #noqa to ignore them.
for moin.constants.* it is pretty ok to do a star import.
=> flake8: enable star import check

src/moin/apps/frontend/views.py, src/moin/converter/markdown_in.py, src/moin/storage/middleware/_tests/test_serialization.py, src/moin/storage/stores/_tests/conftest.py, src/moin/user.py, src/moin/util/crypto.py
=> Fix warnings

src/moin/translations/de/LC_MESSAGES/messages.po
=> some fixes for the german translation

src/moin/converter/_tests/test_moinwiki_in_out.py
will work on test_moinwiki_in_out_todo next
=> remove long test from test_moinwiki_in_out, move parts to other places

setup.cfg, src/moin/converters/_tests/test_markdown_in.py, src/moin/converters/_tests/test_moinwiki_in_out.py, src/moin/converters/_tests/test_rst_in.py, src/moin/converters/html_out.py, src/moin/converters/markdown_in.py, src/moin/utils/_tests/test_subscriptions.py
Related to #605, W605 is the code for "Invalid escape sequence"
=> #605, flake8: Check and fix code W605

src/moin/apps/frontend/views.py, src/moin/static/css/common.css
ajaxdelete and ajaxdestroy have redundant code
=> fixes #731, ajaxdestroy fails to destroy/delete files with non-ascii names

requirements.d/development.txt, src/moin/storage/stores/_tests/conftest.py
=> refactor for Pytest4

contrib/sample/MoinWikiMacros.data, contrib/sample/MoinWikiMacros.meta, docs/user/moinwiki.rst, src/moin/items/__init__.py, src/moin/macros/ItemPageList.py, src/moin/macros/_base.py, src/moin/macros/_tests/test__base.py
1) New ItemPageList macro (superset of existing PagenameList macro functionality).
2) Modified existing methods in a backwards compatable way.
3) Added documentation to some existing methods.
=> New ItemPageList macro

src/moin/storage/middleware/indexing.py
On windows 10 test system handles 7 locusts with 0 errors, 10 locusts with 41 KeyErrors over 560 transactions.
On digitalrockart web site, handles 10 locusts with 0 errors over 560 transactions. Ignoring 12 strange status codes of 0 and 10 status codes of 404 (after user logs in, CentOS tries to serve /Home instead of /moin/Home).
=> fix #479 and #480 process multiple simultaneous updates

contrib/wsgi/moin2.wsgi
Includes a note for the venv path; needs to be addressed...
=> Fixed print syntax for py3

src/moin/config/default.py
this is same value given to anonymous users, followup for #940
=> default RESULTS_PER_PAGE for new users should be 50, not infinity

src/moin/apps/frontend/views.py, src/moin/storage/middleware/protecting.py, src/moin/templates/global_history.html
=> reduce Global History response times by up to 66% #946

src/moin/apps/admin/templates/admin/userbrowser.html, src/moin/apps/admin/views.py, src/moin/static/css/common.css
replace action buttons with icons, beautify html source
=> improve admin/userbrowser report, add subscriptions column,

src/moin/apps/frontend/views.py, src/moin/constants/forms.py, src/moin/forms.py, src/moin/static/css/common.css, src/moin/templates/forms.html
was dropdown list, saves a click, less ugly
=> change theme selection in user preferences to radio buttons

src/moin/apps/frontend/views.py
Also show info message on successful conversion.
=> BF+ENH: Error msg instead of 500 on item conversion failure

src/moin/converters/pdf_in.py
Using default `LAPARAMS` gives as good or better text extraction
with better performance, and in particular much better worst case
performance.  Regardless, the text extraction can still take
minutes so we also stop processing the page prematurely if it is
taking too long.
=> ENH: Greatly reduce worst case PDF text extraction time

src/moin/converters/_tests/test_markdown_in_out.py, src/moin/converters/markdown_out.py
add tests to test_markdown_in_out.py
=> fix missing title attribute after markdown to markdown conversion

quickinstall.py
correct some comments, change variable names needed for virtualenv to venv
conversion
=> virtualenv 20.0.0 breaks quickinstall.py, fixes #1036

docs/user/accounts.rst, src/moin/apps/frontend/views.py, src/moin/templates/mychanges.html, src/moin/templates/utils.html
links in mychanges.html point to changed revisions, not last revision
=> enhance mychanges.html, remove todos from docs/user/accounts.rst

src/moin/app.py, src/moin/apps/frontend/views.py, src/moin/converters/_tests/test_markdown_in.py, src/moin/converters/_tests/test_markdown_in_out.py, src/moin/templates/sitemap.html
show missing items in gray text
sort by item names
show namespace in item name
=> improve speed and functionality of sitemap #1069

src/moin/storage/middleware/indexing.py
=> index field comments updated to reflect blog-only, ticket-only usage

src/moin/apps/frontend/views.py, src/moin/items/__init__.py, src/moin/items/_tests/test_Item.py, src/moin/static/css/common.css, src/moin/static/js/index_action.js, src/moin/static/js/jfu.js, src/moin/storage/middleware/indexing.py, src/moin/templates/index.html
item size, modified time, number revisions added
=> change Index from UL to sortable table, add more fields, fixes #216

src/moin/app.py, src/moin/apps/admin/templates/admin/trash.html, src/moin/apps/admin/views.py, src/moin/apps/frontend/views.py, src/moin/items/__init__.py, src/moin/items/_tests/test_Item.py, src/moin/items/content.py, src/moin/static/css/common.css, src/moin/templates/delete.html, src/moin/templates/rename.html
added tip to rename view, improved title of delete view fixes #880
number 11 of the 13 steps in issue 81 is fixed
=> Rename and Delete now support alias names like Item Modify fixes #580

src/moin/config/wikiconfig.py
intermap "missing" with first exec of `moin create-instance` after pip
install from test.pypi
=> improve wikiconfig.py comments, workaround missing intermap.txt

src/moin/storage/middleware/indexing.py
=> add field_boost=200.0 to tags and summary; improves whoosh scoring #1073

src/moin/scripts/migration/moin19/import19.py, src/moin/scripts/migration/moin19/macro_migration.py, src/moin/scripts/migration/moin19/macros/PageList.py
In response to #1174 I have made an attempt to implement the idea of a macro migration. I'd appreciate a review on whether this would be an acceptable way to go.
=> Implement migration for moin1.9 PageList macro

src/moin/translations/MoinMoin.pot, src/moin/translations/de/LC_MESSAGES/messages.po, src/moin/translations/pt_BR/LC_MESSAGES/messages.po, src/moin/translations/ru/LC_MESSAGES/messages.po
run extract_messages, update_catalog and
remove wrong fuzzy results and unused translations
=> Update translations and fix unknown named placeholder warnings

docs/admin/install.rst, docs/admin/requirements.rst, moin.spec, quickinstall.py, src/moin/__init__.py
Some more references adapted for python from version 3.5 to 3.8
=> require python 3.8+

docs/conf.py
=> Set autosummary_generate = False

docs/user/docbook.rst
=> Update docbook.rst from sample docs

requirements.d/development.txt
=> remove pytest-pep8

src/moin/constants/contenttypes.py, src/moin/items/__init__.py
only en help items available now
=> load help for editors based upon user's language #1155

src/moin/macros/RandomItem.py, src/moin/macros/_base.py, src/moin/macros/_tests/test_ItemList.py
Fix ItemList with namespace and add test for ItemList macro. 
Adapt RandomItem macro.
=> Fix ItemList with namespace, add test, fixes #1222

src/moin/storage/middleware/_tests/test_indexing.py, src/moin/storage/middleware/indexing.py
=> Optimize performance in test_destroy_revision

src/moin/items/__init__.py
In `items/__init__.py`: 
- fixed flake8 warnings F401 and F841
- more specific query to narrow result list for wiki_matches()
Fixes #1225
=> narrow search in find_matches()

src/moin/macros/ItemList.py, src/moin/macros/_tests/test_ItemList.py
=> Fix ItemList macro with regex, add test

src/moin/help/en/creole.data, src/moin/help/en/creole.meta, src/moin/help/en/moin.data, src/moin/help/en/moin.meta
fixed bad links, more examples
=> improve help-en/moin and help-en/creole items #1258

src/moin/storage/middleware/indexing.py
=> Consider namespace in convert_to_indexable

src/moin/_tests/__init__.py, src/moin/storage/middleware/_tests/test_indexing.py
This is the test for meta itemlinks as stated in #1258.
=> Add test for itemlinks in meta

setup.cfg, src/moin/_tests/ldap_testbase.py, src/moin/_tests/test_test_environ.py, src/moin/_tests/test_user.py, src/moin/apps/admin/views.py, src/moin/apps/feed/views.py, src/moin/apps/frontend/_tests/test_frontend.py, src/moin/apps/frontend/views.py, src/moin/auth/ldap_login.py, src/moin/converters/_wiki_macro.py, src/moin/converters/include.py, src/moin/converters/markdown_out.py, src/moin/converters/mediawiki_in.py, src/moin/converters/moinwiki_out.py, src/moin/converters/rst_in.py, src/moin/converters/rst_out.py, src/moin/items/_tests/test_Content.py, src/moin/items/_tests/test_Item.py, src/moin/items/blog.py, src/moin/items/content.py, src/moin/macros/RandomItem.py, src/moin/macros/ShowIcons.py, src/moin/scripts/migration/moin19/import19.py, src/moin/storage/middleware/_tests/test_indexing.py, src/moin/storage/middleware/validation.py, src/moin/storage/stores/_tests/test_sqla.py, src/moin/storage/stores/_tests/test_sqlite.py, src/moin/utils/_tests/test_thread_monitor.py, src/moin/utils/interwiki.py, src/moin/utils/notifications.py
=> flake8: Check and fix F841

src/moin/utils/monkeypatch.py
=> Change werkzeug BaseRequestHandler to WSGIRequestHandler

src/moin/app.py
Fixes `moin help` command failure from #1270.
=> fix moin help in create_app_ext

setup.cfg, src/moin/scripts/migration/moin19/_logfile19.py, src/moin/scripts/migration/moin19/_utils19.py
=> Reduce flake8 exeptions in setup.cfg

setup.cfg, src/moin/auth/_tests/test_ldap_login.py, src/moin/forms.py, src/moin/items/ticket.py, src/moin/signalling/log.py, src/moin/user.py, src/moin/utils/_tests/test_mime.py, src/moin/utils/rev_navigation.py
... and some long lines.
Related to #605.
=> Fix flake8 warnings F405

quickinstall.py
=> fix flake8 findings in quickinstall.py

setup.py, src/moin/converters/_tests/test_markdown_in_out.py
=> Add workaround for Markup dep

src/moin/converters/_tests/test_markdown_in_out.py, src/moin/storage/middleware/indexing.py
Fixes flake8 warnings from recent updates #1292 and #1293
=> Fix flake8 warnings

src/moin/scripts/migration/moin19/import19.py
Try to fix #1305.
Update of docs will follow.
=> import19.py: fix itemlinks for users namespace

docs/admin/upgrade.rst
=> Upgrade docs: Remove broken itemlinks section, improve formatting

src/moin/translations/de/LC_MESSAGES/messages.po
Adds some german translations, although not all. Does not change any existing ones. I'm unsure on some translations but it's a start. Part of https://github.com/moinwiki/moin/issues/651
=> Adds some german translation

src/moin/app.py, src/moin/storage/stores/_tests/test_fs.py, src/moin/storage/stores/_tests/test_memory.py, src/moin/storage/stores/_tests/test_sqla.py, src/moin/storage/stores/_tests/test_sqlite.py
=> Fix pytest warnings about flask_caching and PytestReturnNotNoneWarning

docs/requirements.txt
Workaround for #1333 and as discussed in  #1336.
Waiting for sphinx-rtd-theme final version 1.2.0
=> Temporary fix for sphinx-rtd-theme

quickinstall.py, requirements.d/docs.txt, requirements.d/extras.txt, requirements.d/ldap.txt, setup.py
Fixes #1339, additionally
- removed sqlalchemy from quickinstall.py as it is included in setup.py
- removed unused function get_sitepackages_location()
=> Cleanup of requirements handling

src/moin/macros/ItemList.py
old method added tracebacks to server log; Item not found could be a good thing
=> convert item not found exception err to admonition msg in ItemList macro

src/moin/apps/frontend/views.py
simplify login processing and remove dead code
=> convert Flatland String object to str; fixes: #1345

src/moin/scripts/account/disable.py, src/moin/user.py
=> Fix account-disable command

docs/admin/serve.rst, docs/examples/deployment/moin.fcgi, docs/examples/deployment/moin.wsgi
Fixes: https://github.com/moinwiki/moin/issues/1349
=> updating imports in docs, fixes #1349

src/moin/converters/_tests/test_markdown_in.py, src/moin/converters/_tests/test_markdown_in_out.py, src/moin/converters/markdown_in.py, src/moin/converters/markdown_out.py
fix tests, improve markdown > markdown conversion for links
=> add missing itemlinks in markdown item's metadata; #1259

src/moin/storage/backends/stores.py
revert changes to storage/backends/stores.py made by #1234
=> moin maint-reduce-revisions removes item content; fixes #1351

src/moin/converters/_tests/test_docbook_in.py, src/moin/converters/docbook_in.py, src/moin/converters/html_out.py, src/moin/converters/include.py, src/moin/converters/link.py
docbook transclusions use xinclude
same as moinwiki
data-href now processed
thru link.ConverterExternOutput
same as xlink.href
=> fixes #167 for docbook and data-href

src/moin/storage/stores/_tests/test_fs.py, src/moin/storage/stores/_tests/test_memory.py, src/moin/storage/stores/_tests/test_sqla.py, src/moin/storage/stores/_tests/test_sqlite.py
=> Change pytest.mark.multi to mark.parametrize

src/moin/cli/migration/moin19/import19.py
=> Add optimize_index to import19

setup.py, src/moin/items/_tests/test_Blog.py
=> Update Werkzeug to 2.2.3

src/moin/items/_tests/test_Blog.py
=> test_Blog.py: revert Werkzeug 2.2.3 workaround

src/moin/cli/__init__.py, src/moin/cli/maint/modify_item.py, src/moin/help/__init__.py, src/moin/help/welcome/Home.data, src/moin/help/welcome/Home.meta
Related to #1381.
The new command is `moin welcome`
=> CLI: Add command to create an initial welcome page

src/moin/cli/__init__.py, src/moin/cli/maint/create_instance.py, src/moin/cli/maint/index.py, src/moin/cli/maint/modify_item.py
This is a proposal for #1381. I'm interested in your opinion. 
Maybe there is a better name for the new option.
=> CLI: add create-instance option --full 

src/moin/app.py, src/moin/conftest.py
In app.py: 
- replace sys.argv with info_name
- remove options -i and -s (parameter create_index and create_storage)
Fixes #1386.
=> app.py: replace sys.argv and remove options -i and -s

.github/workflows/ci.yml
=> ci.yml: update actions versions

src/moin/config/default.py
=> default.py: remove obsolete index and storage options

src/moin/cli/maint/modify_item.py
=> CLI: check if Home item exists when running moin welcome

src/moin/apps/feed/views.py
=> feed: use fqname.fullname and mark content as type html

src/moin/cli/maint/dump_html.py
added "with app.test_request_context():"; many lines of code indented
=> fix `moin dump-html` #729

setup.py, src/moin/translations/MoinMoin.pot, src/moin/translations/de/LC_MESSAGES/messages.po
and add some more translations.
Fixes #1427.
=> translations: change type of dictionary.js to jinja2 

src/moin/cli/maint/dump_html.py
=> Fix moinmoin directory path

src/moin/cli/maint/create_instance.py, src/moin/cli/maint/modify_item.py
=> fix load help in create-instance --full

src/moin/app.py, src/moin/cli/__init__.py, src/moin/cli/maint/create_instance.py
=> Fix path in create-instance with --full option

docs/conf.py
=> Fix location of logo and favicon for make html

src/moin/macros/_tests/test_DateTime.py
=> fix for test_DateTime failure, fixes 1450

src/moin/cli/maint/dump_html.py
Related to #1452.
Needs further tests on Windows.
You may feel free to do a quality check of the code. Sometimes I have trouble finding suitable names for variables and functions. Any suggestions are welcome.
=> dump-html optimization

README.rst
=> Update README and add link to readthedocs

src/moin/i18n/__init__.py
=> eliminate '_request_ctx_stack' is deprecated message #1486

src/moin/cli/migration/moin19/import19.py, src/moin/cli/migration/moin19/macros/MonthCalendar.py, src/moin/converters/_wiki_macro.py
=> import19: use logging, optimize output and add stats

requirements.d/development.txt
=> require scrapy version >= 2.10.1

MANIFEST.in
related to #609.
Travis was removed in #1082.
=> remove .travis.yml from MANIFEST.in

setup.py, src/moin/converters/pdf_in.py
Fixes #1507
Many thanks to Paul B. from Debian development for providing this solution.
=> Use pdfminer instead of pdfminer3

setup.py, src/moin/apps/frontend/views.py, src/moin/i18n/__init__.py, src/moin/i18n/_tests/test_i18n.py
Fixes #1506.
By the way, the blinker version has been raised to 1.5 to help pip find the right version.
=> Upgrade Flask-Babel to 3.x

src/moin/macros/_tests/test_Date.py, src/moin/utils/_tests/test_show_time.py
=> Use more conventional time zones

src/moin/themes/basic/templates/modify.html
adds a preview-button and show the preview data in the template
fixes moinwiki/moin#1521
=> basic theme: add preview

src/moin/converters/opendocument_in.py
=> opendocument_in: handle AttributeError

scripts/coding_std.py
=> coding_std.py: exclude dictionary.js from check_js_phrases

src/moin/config/default.py, src/moin/templates/convert.html, src/moin/templates/history.html, src/moin/templates/modify_meta.html, src/moin/templates/revert.html, src/moin/templates/search.html, src/moin/templates/snippets.html
=> Add missing and fix some localization 

setup.cfg, src/moin/translations/MoinMoin.pot, src/moin/translations/de/LC_MESSAGES/messages.po
This PR changes the width parameter for extract_messages and update_messages to 116 resulting in a maximum line length of about 120 characters. This avoids a lot of line breaks in the translation files.
Related to #651.
=> Add more German translations

setup.py, src/moin/auth/__init__.py, src/moin/converters/image_in.py, src/moin/utils/send_file.py
=> Raise werkzeug to 3.0 and remove werkzeug.urls usage

src/moin/themes/basic/static/css/theme.css, src/moin/themes/basic/static/custom-less/theme.less, src/moin/themes/modernized/static/css/theme.css
=> Reduce permalink font-size

src/moin/cli/migration/moin19/import19.py
Related to #1488
Fixes the count of revisions, was number of items before.
Adds the count of attachments and debug messages with attachment names.
=> import19: fix revs stats & add attachments stats and logging

src/moin/cli/migration/moin19/import19.py
... and use keys from constants.
Fixes #1574.
=> import19.py: add user session_token if missing

docs/admin/configure.rst, docs/examples/config/wikiconfig.py, src/moin/config/wikiconfig.py
fixes #1555 fixes #623
reordered wikiconfig.py to move namespace ACLs under registration options
=> change wikiconfig.py default registration_only_by_superuser=True

src/moin/macros/ShowSmileys.py, src/moin/macros/_tests/test_ShowSmileys.py
related to #1585. Started with the easiest. :smirk:
I am not really satisfied with the test. I would prefer to check the HTML output, but I need help with this.
=> Add ShowSmileys macro

.github/workflows/ci.yml
=> Github CI workflow: update actions versions

docs/user/moinwiki.rst, src/moin/help/help-en/MoinWikiMacros.data, src/moin/help/help-en/MoinWikiMacros.meta
=> Add docs for ShowIcons and TitleIndex macros

src/moin/translations/MoinMoin.pot, src/moin/translations/de/LC_MESSAGES/messages.po
=> Update and add German translations

src/moin/app.py, src/moin/cli/maint/create_instance.py, src/moin/cli/maint/index.py, src/moin/utils/filesys.py
=> Add wiki index checks in CLI.

docs/devel/translate.rst
=> Upd devel/translate docs

src/moin/config/default.py, src/moin/config/wikiconfig.py, src/moin/items/_tests/test_Content.py, src/moin/items/_tests/test_Item.py, src/moin/items/content.py
... and revert #1501.
Related to #1500.
=> Add config option to enable or disable contenttypes

docs/admin/install.rst
=> update docs for moin2 installation, add section on Verifying signed

src/moin/help/welcome/users-Home.meta
=> Remove parentid to fix welcome/users-Home.meta

.pre-commit-config.yaml, contrib/loadtesting/locust/locustfile.py, src/moin/apps/frontend/views.py, src/moin/converters/archive_in.py, src/moin/forms.py, src/moin/macros/_tests/test_Date.py, src/moin/macros/_tests/test_DateTime.py, src/moin/storage/middleware/indexing.py, src/moin/utils/__init__.py, src/moin/utils/show_time.py
Fixes #1675.
Also: pre-commit: switch from flake8 to ruff.
=> work around some datetime deprecation warnings

src/moin/apps/frontend/views.py
also: remove duplicate "en" entry.
fixes #1531.
=> personal settings: add language auto-detect

.github/workflows/ci.yml
=> Fix CI workflow, run py39 with ubuntu 22.04

src/moin/apps/frontend/views.py
=> Add REV_NUMBER in sort for history view

src/moin/storage/middleware/indexing.py, src/moin/storage/middleware/validation.py
=> Add itemlinks validator

src/moin/macros/_tests/test_ShowIcons.py
=> Test if icons from css urls is a subset of filenames in icon dir

src/moin/static/css/common.css, src/moin/templates/global_history.html
=> Add RSS link to global history

src/moin/apps/frontend/views.py, src/moin/constants/misc.py, src/moin/items/content.py, src/moin/macros/SlideShow.py, src/moin/static/css/projection.css, src/moin/templates/slideshow.html
Related to #1585.
TODOs:
- Add macro to help-en pages
- Add macro to readthedocs
- Add macro conversion
- Add JavaScript function to use cursor keys for navigation
=> Add SlideShow macro and view

docs/changes/CHANGES
=> Update CHANGES, shooting for 2.0.0b1 release 2024-08-07 #1616

docs/user/moinwiki.rst, src/moin/help/help-en/MoinWikiMacros.data, src/moin/help/help-en/MoinWikiMacros.meta, src/moin/templates/slideshow.html
Related to #1585.
TODO: Add to macro conversion
=> SlideShow macro: add docs and key control

src/moin/cli/maint/dump_html.py, src/moin/constants/contenttypes.py
=> dump-html: dump raw data for pdf, tar and others

src/moin/converters/moinwiki_in.py
=> Ignore empty table attributes in moinwiki_in

src/moin/items/__init__.py
Related to #1735.
@ThomasWaldmann: please check, as the comment has been fundamentally changed.
=> fix list of dirs returned by make_flat_index

src/moin/cli/migration/moin19/import19.py
=> import19: add namespace for attachments

src/moin/apps/admin/_tests/test_admin.py, src/moin/apps/admin/views.py
This is related to the first 3 admin views mentioned in #1734.
=> Restrict all admin views to the superuser

src/moin/app.py
=> app.py: set url_map.strict_slashes to False

src/moin/storage/middleware/indexing.py
=> Fix convert_to_indexable for items in a namespace

src/moin/converters/highlight.py
=> Highlight search results: treat each word separately and ignore case

src/moin/apps/frontend/views.py
=> add missing attribute 'may' to diff.html template

docs/admin/upgrade.rst, src/moin/cli/migration/moin19/import19.py
=> import19: add option latest-rev-only

src/moin/converters/_args_wiki.py
=> _args_wiki parse: ignore keys with empty value

src/moin/themes/__init__.py
This is a leftover from #1782.
=> Fix traceback when viewing item with @itemid

src/moin/utils/crypto.py, src/moin/utils/plugins.py
=> add usedforsecurity False in hash functions

src/moin/storage/middleware/indexing.py
=> indexing.py: Narrow down the broad exception

src/moin/config/default.py, src/moin/themes/__init__.py
Related to #1820.
If this function is requested again, some effort is required to ensure secure handling of the URLs.
=> Remove sistersite feature.

.pre-commit-config.yaml, docs/devel/development.rst, pyproject.toml
=> Add pre-commit for bandit security scan

src/moin/templates/itemviews.html
Fix the issue described in #1847
=> Fix duplicate namespace in discussion link (#1847)

docs/devel/development.rst, src/moin/static/css/common.css, src/moin/templates/modify.html
plus 2 fixes generated by "./m coding-std"
=> add "pre-commit run" to development.rst docs

docs/admin/configure.rst, src/moin/apps/frontend/views.py
Correction of 2 small wording problems that I noticed yesterday.
=> Small corrections

src/moin/templates/ajaxsearch.html
=> ajaxsearch: add check whether content exists

src/moin/apps/admin/templates/admin/trash.html, src/moin/config/default.py, src/moin/converters/html_in.py, src/moin/templates/crash.html, src/moin/translations/MoinMoin.pot, src/moin/translations/de/LC_MESSAGES/messages.po, src/moin/translations/pt_BR/LC_MESSAGES/messages.po, src/moin/translations/ru/LC_MESSAGES/messages.po
See the discussion in issue #1860.
=> Replace text "Highlight" with "Markup" (#1860)

src/moin/apps/frontend/views.py, src/moin/static/js/common.js
This is an attempt to fix the flaws found in #1872.
=> User settings: fix handling of flash messages (#1872)

src/moin/templates/utils.html
Picking up the suggestion to improve readability made in #1770.
=> Render item metadata as a table

src/moin/config/wikiconfig.py
=> wikiconfig.py: Add comment on deactivation of discussion feature

src/moin/apps/frontend/views.py
=> Fix build of query in tagged_items() if namespace is 'all'

src/moin/themes/focus/static/css/theme.css
Fixes #1904. Additionally this PR ensures that the navigation will be hidden.
=> Improve print layout for focus theme

src/moin/constants/misc.py, src/moin/themes/__init__.py
=> add icon for +admin/user and some fault tolerance

src/moin/static/js/slideshow.js, src/moin/templates/slideshow.html
=> Move slideshow inline js script to separate file

src/moin/themes/topside/static/css/theme.css
=> topside: fix footer width on small screen

src/moin/themes/focus/static/css/theme.css
=> Fix empty lines in diff in focus theme

src/moin/_tests/__init__.py
=> get_open_wiki_files: add file mode to output for debugging

src/moin/utils/monkeypatch.py
Related to #1961.
@roland-ruedenauer, thanks for the code template.
=> Add buffer reset to whoosh Bufferfile.close
